services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw
      - ./DB/Management.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./DB/Database_Init.sh:/docker-entrypoint-initdb.d/create_db.sh:ro
    environment:
      # POSTGRES_PASSWORD_FILE: ./postgress/postgres-passwd
      POSTGRES_PASSWORD: GIGALIB258
      POSTGRES_USER: admin
    ports:
      - "5432:5432"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: GIGALIB258
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  manage_identity:
    build:
      context: .
      dockerfile: Manage/Manage.Identity/Dockerfile
    environment:
      POSTGRES_CONNECTION: "Host=postgres;Port=5432;User ID=admin;Password=GIGALIB258;Database=Identity"
      REDIS_CONNECTION: "redis:6379"
      MINIO_CONNECTION: "minio:9000"
      MINIO_ACCESSKEY: "ROOTUSER"
      MINIO_SECRETKEY: "GIGALIB258"
      KAFKA_CONNECTION: "kafka:9092"
      JWT_AUDIENCE: "websgram.ir"
      JWT_ISSUER: "websgram.ir"
      JWT_KEY: "1!=}X!fEBBDxZW;"
      EMAIL_CREDENTIALS: "W?&l9Y2"
      EMAIL_ADDRESS: "info@websgram.com"
      EMAIL_HOST: "mail.websgram.ir"
      EMAIL_NAME: "Websgram"
      SMS_USERNAME: "HEYHEYHEY"
      SMS_PASSWORD: "GIGALIB258"
      SMS_PHONENUMBER: "0000000000000"
    depends_on:
      - kafka
      - redis
      - postgres
      - minio
    ports:
      - "5000:8080"
      - "5001:8081"
